name: flutter_rebuild_mre
# https://github.com/flutter/flutter/issues/132424
description: Minimal reproducible example for Flutter rebuild issue #132424
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
